import React from 'react';
import type { Deal, Creator, Deliverable, Report } from '../types/creatorops';
import { 
  Check, 
  Sparkles, 
  Eye, 
  ThumbsUp, 
  MessageSquare, 
  ArrowLeft,
  Share2,
  ExternalLink
} from 'lucide-react';

interface PublicReportViewProps {
  deal: Deal;
  creators: Creator[];
  deliverables: Deliverable[];
  report: Report;
  onBackToApp?: () => void;
}

export const PublicReportView: React.FC<PublicReportViewProps> = ({
  deal,
  creators,
  deliverables,
  report,
  onBackToApp
}) => {
  const [copied, setCopied] = React.useState(false);

  const attachedCreators = creators.filter(c => deal.creatorIds.includes(c.id));
  const dealDeliverables = deliverables.filter(d => d.dealId === deal.id);

  const totalViews = dealDeliverables.reduce((sum, d) => sum + (d.finalMetrics.views || 0), 0);
  const totalLikes = dealDeliverables.reduce((sum, d) => sum + (d.finalMetrics.likes || 0), 0);
  const totalComments = dealDeliverables.reduce((sum, d) => sum + (d.finalMetrics.comments || 0), 0);

  const engagementRate = totalViews > 0 
    ? (((totalLikes + totalComments) / totalViews) * 100).toFixed(2) 
    : '0.00';

  const copyShareLink = () => {
    const url = `${window.location.origin}/report/${report.publicSlug}`;
    navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="min-h-screen bg-[#F8FAFC] text-[#0F172A] font-sans antialiased p-4 md:p-8 select-none">
      <div className="max-w-4xl mx-auto mb-6 flex items-center justify-between">
        {onBackToApp ? (
          <button
            onClick={onBackToApp}
            className="flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-ink bg-white border border-slate-200 px-3 py-1.5 rounded-lg shadow-subtle transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Dashboard</span>
          </button>
        ) : (
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-indigo-600 flex items-center justify-center text-white font-bold text-xs">
              <Sparkles className="w-3.5 h-3.5" />
            </div>
            <span className="text-xs font-bold tracking-tight text-slate-500">Apex Creator Agency • Official Report</span>
          </div>
        )}

        <button
          onClick={copyShareLink}
          className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold px-4 py-2 rounded-lg shadow-subtle transition-all"
        >
          {copied ? <Check className="w-4 h-4 text-emerald-300" /> : <Share2 className="w-4 h-4" />}
          <span>{copied ? 'Link Copied!' : 'Copy Shareable Report Link'}</span>
        </button>
      </div>

      <main className="max-w-4xl mx-auto bg-white border border-slate-200 rounded-2xl shadow-modal overflow-hidden">
        <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white p-8 border-b border-slate-200 relative">
          <div className="flex items-center justify-between flex-wrap gap-4">
            <div>
              <span className="text-xs font-bold text-indigo-300 uppercase tracking-widest bg-indigo-900/60 px-3 py-1 rounded-full border border-indigo-700/50 inline-block mb-3">
                Campaign Deliverable Summary
              </span>
              <h1 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight">{deal.brandName} Sponsorship</h1>
              <p className="text-xs text-slate-300 mt-1">
                Generated by Apex Creator Agency • {new Date(report.generatedAt).toLocaleDateString()}
              </p>
            </div>

            <div className="flex items-center -space-x-3">
              {attachedCreators.map(c => (
                <img
                  key={c.id}
                  src={c.photoUrl}
                  alt={c.name}
                  className="w-12 h-12 rounded-full border-2 border-white object-cover shadow-card"
                  title={c.name}
                />
              ))}
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 divide-x divide-y md:divide-y-0 divide-slate-100 border-b border-slate-200 bg-slate-50/50">
          <div className="p-6 text-center">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-1 flex items-center justify-center gap-1">
              <Eye className="w-3.5 h-3.5 text-indigo-600" />
              Total Views / Reach
            </span>
            <span className="text-2xl md:text-3xl font-black text-slate-900 font-mono tabular-nums">
              {totalViews.toLocaleString()}
            </span>
          </div>

          <div className="p-6 text-center">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-1 flex items-center justify-center gap-1">
              <ThumbsUp className="w-3.5 h-3.5 text-emerald-600" />
              Total Likes
            </span>
            <span className="text-2xl md:text-3xl font-black text-slate-900 font-mono tabular-nums">
              {totalLikes.toLocaleString()}
            </span>
          </div>

          <div className="p-6 text-center">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-1 flex items-center justify-center gap-1">
              <MessageSquare className="w-3.5 h-3.5 text-purple-600" />
              Comments
            </span>
            <span className="text-2xl md:text-3xl font-black text-slate-900 font-mono tabular-nums">
              {totalComments.toLocaleString()}
            </span>
          </div>

          <div className="p-6 text-center">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-1">
              Engagement Rate
            </span>
            <span className="text-2xl md:text-3xl font-black text-indigo-600 font-mono tabular-nums">
              {engagementRate}%
            </span>
          </div>
        </div>

        <div className="p-8 space-y-6">
          <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-3">
            Campaign Deliverables ({dealDeliverables.length})
          </h2>

          <div className="space-y-4">
            {dealDeliverables.map((deliv) => {
              const creator = attachedCreators.find(c => c.id === deliv.creatorId);

              return (
                <div key={deliv.id} className="bg-slate-50 border border-slate-200 rounded-xl p-5 space-y-4 shadow-subtle">
                  <div className="flex items-start justify-between gap-4 flex-wrap">
                    <div className="flex items-center gap-3">
                      {creator && (
                        <img src={creator.photoUrl} alt={creator.name} className="w-10 h-10 rounded-full object-cover border border-slate-300" />
                      )}
                      <div>
                        <h3 className="text-sm font-bold text-slate-900">{deliv.title}</h3>
                        <p className="text-xs text-slate-500 mt-0.5">
                          {creator?.name} • <span className="font-semibold text-slate-700">{deliv.platform}</span> • Status: <span className="text-emerald-600 font-bold">{deliv.status}</span>
                        </p>
                      </div>
                    </div>

                    {deliv.liveUrl && (
                      <a
                        href={deliv.liveUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-white border border-slate-200 hover:border-indigo-600 text-indigo-600 text-xs font-semibold rounded-lg shadow-subtle transition-all"
                      >
                        <span>View Published Content</span>
                        <ExternalLink className="w-3.5 h-3.5" />
                      </a>
                    )}
                  </div>

                  <div className="grid grid-cols-3 gap-3 bg-white p-3 rounded-lg border border-slate-200 text-center text-xs">
                    <div>
                      <p className="text-[10px] text-slate-400 font-semibold uppercase">Views</p>
                      <p className="font-bold text-slate-900 font-mono text-sm mt-0.5">{deliv.finalMetrics.views.toLocaleString()}</p>
                    </div>
                    <div>
                      <p className="text-[10px] text-slate-400 font-semibold uppercase">Likes</p>
                      <p className="font-bold text-slate-900 font-mono text-sm mt-0.5">{deliv.finalMetrics.likes.toLocaleString()}</p>
                    </div>
                    <div>
                      <p className="text-[10px] text-slate-400 font-semibold uppercase">Comments</p>
                      <p className="font-bold text-slate-900 font-mono text-sm mt-0.5">{deliv.finalMetrics.comments.toLocaleString()}</p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        <div className="p-6 bg-slate-100 border-t border-slate-200 text-center text-xs text-slate-500">
          Report generated by Apex Creator Agency • Managed with CreatorOps Workspace
        </div>
      </main>
    </div>
  );
};
